# Generated by Django 2.2 on 2019-04-05 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20190405_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ['name']},
        ),
    ]
